### ISSUE TITLE
parseArray bugs... sometimes

### ISSUE THREAD

**Issue by RobinDev** [cheprasov/php-cli-args#7]
Very hard to explain ! Sometimes the method `CliArgs::parseArray` not finished to parse `$argv`. Like if the while bugs.

If I replace `while ($arg = array_shift($argv)) {` by `foreach ($argv as $arg) {` every thing work perfectly...

An idea why.

Example not working, used with [this package](https://github.com/PiedWeb/SeoPocketCrawler) :
```
bin/crawler --start https://github.com/ -i "cache/notimage.txt" -w 0 -u spider -l 100
```

**Comment by cheprasov** [comment]
Hi @RobinDev 
Thank a lot for feedback, I will check it soon.
